
# 作者
author: Neo
name: 倪云港
github: http://github.com/niyungang
email: yungangni@gmail.com

# 配置
paginate: 12
paginate_path: "blog/page:num"

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]
highlighter: rouge
markdown: kramdown 
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# 自定义变量
domain: "http://xgcyjd2015.github.io"

# 站点信息
title: 信管创业基地
description: 信管创业基地官方博客
url: http://xgcyjd2015.github.io
site: http://xgcyjd2015.github.io
link: http://xgcyjd2015.github.io

# rss
rss_url: /feed.xml